# Generated by Django 4.2.11 on 2024-05-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shopping_car',
            new_name='is_in_shopping_cart',
        ),
    ]
