# Generated by Django 4.2.11 on 2024-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.SlugField(editable=False, max_length=6, unique=True),
        ),
    ]
