# Generated by Django 4.2.11 on 2024-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_link_short_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='short_link',
        ),
        migrations.AddField(
            model_name='link',
            name='short_code',
            field=models.SlugField(blank=True, max_length=5, unique=True),
        ),
    ]
