# Generated by Django 4.2.11 on 2024-05-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_rename_is_in_shopping_car_recipe_is_in_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(blank=True, null=True, verbose_name='В избранном'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(blank=True, null=True, verbose_name='В списке покупок'),
        ),
    ]
