# Generated by Django 4.2.11 on 2024-05-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_rename_author_favorite_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient'),
        ),
    ]
