# Generated by Django 4.2.11 on 2024-05-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_link_original_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(choices=[('г', 'Граммы'), ('капля', 'Капля'), ('шт.', 'Штуки'), ('кусок', 'Кусок'), ('мл', 'Миллилитры'), ('ч.л.', 'Чайная ложка')], max_length=128),
        ),
    ]
