# Generated by Django 4.2.11 on 2024-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_recipe_is_favorited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_favorited',
            field=models.BooleanField(blank=True, null=True, verbose_name='В избранном'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.BooleanField(blank=True, null=True, verbose_name='В списке покупок'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
