# Generated by Django 4.2.11 on 2024-05-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_is_favorited_recipe_is_in_shopping_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
